### ISSUE TITLE
Character with custom graffiti sprays Red's tag instead

### ISSUE THREAD

**Issue by WyattTheOtter** [viliger2/CharacterAPI_BRCCCLoader#1]
Hello! I tried importing my model with this, the model replaces Solace, but when i loaded into the game and chose my character, their custom graffiti was replaced with Reds default tag instead, but solaces voice was still working just fine

**Comment by viliger2** [comment]
Send an asset bundle my way, I'll take a look.

**Comment by WyattTheOtter** [comment]
[felix_solace.zip](https://github.com/viliger2/CharacterAPI_BRCCCLoader/files/12643283/felix_solace.zip)
will this work?

**Comment by viliger2** [comment]
```[Warning:CharacterAPI] Personal graffiti Felix's name for character Felix collides with existing game graffiti. Skipping personal graffiti...```
You can't have custom graffiti have the same name as game's graffiti for custom characters, the game will get confused. Rename it to something else.  I've attached a spreadsheet with all graffiti, their names and sizes, but as a general rule all personal graffiti have the same name as their owners.
[graffiti.csv](https://github.com/viliger2/CharacterAPI_BRCCCLoader/files/12643294/graffiti.csv)

**Comment by WyattTheOtter** [comment]
Ah I see, yeah I’ll go change the name then lol, thank you!
