### ISSUE TITLE
custom characters not loading...

### ISSUE THREAD

**Issue by JooZehh** [viliger2/CharacterAPI_BRCCCLoader#2]
Forgive me if I'm misunderstanding but this mod makes it possible to use custom characters that replace characters from brc. If so, I've followed the instructions posted on your page and no method works to add said custom characters as their unique characters. is there a way to fix this?

**Comment by viliger2** [comment]
You need to put your prefabs inside CharacterAPI\BrcCustomCharacters folder in your BepIn folder. Prefabs should not be in any subfolder. If you still don't have characters - attach a log.

**Comment by viliger2** [comment]
@JooZehh I accidentally closed the issue, sorry about that.

**Comment by JooZehh** [comment]
just to make sure, that's the files that include naming such as "asset_character" right, like for example dante_felix. Are these the files that should be in the characterapi folder?

**Comment by viliger2** [comment]
Yes, they should be inside CharacterAPI\BrcCustomCharacters specifically if we are talking about characters made for BRCCC.

**Comment by JooZehh** [comment]
ok yeah it didn't work. i found specifically the log talking about BRCCCloader and will post it here

" [Error  : Unity Log] MissingFieldException: Field not found: string BrcCustomCharactersLib.CharacterDefinition.GraffitiArtist Due to: Could not find field in class
Stack trace:
CharacterAPI_BRCCCLoader.BRCCLoader.LoadBrcCCharacters (System.String pluginPath) (at F:/Projects/CharacterAPI_BRCCCLoader/BRCCustomCharactersLoader/BRCCLoader.cs:113)
CharacterAPI_BRCCCLoader.BRCCLoader.Awake () (at F:/Projects/CharacterAPI_BRCCCLoader/BRCCustomCharactersLoader/BRCCLoader.cs:43)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
DG.Tweening.DOTween:Init(Nullable`1, Nullable`1, Nullable`1)
Reptile.Bootstrap:InitializeDoTween()
Reptile.Bootstrap:Awake()

**Comment by viliger2** [comment]
You have two options:
- Update your BRCCC mod to the latest version, which should be 2.2.2.
- Disable BRCCC completely

This happens due to dll mismatch between older and newer versions of BRCCC, since it loads first, it loads its own version of BrcCustomCharactersLib.dll and if you have older version of BRCCC then it lacks necessary fields for plugin to work.

**Comment by JooZehh** [comment]
ohhhhhhhhhhhhhhhhh ok. yeah i realized that brccc plugin was not downloaded through r2mdman so i deleted it and it worked!
