### ISSUE TITLE
Isnt Working

### ISSUE THREAD

**Issue by arrigit** [viliger2/CharacterAPI_BRCCCLoader#3]
So, i did everything said in the tutorial, and put the custom mods on the intended file, but when i launch the game the custom models doesnt appears.

**Comment by viliger2** [comment]
Post the log. You can find it inside BepInEx folder.

**Comment by arrigit** [comment]
[LogOutput.log](https://github.com/viliger2/CharacterAPI_BRCCCLoader/files/12785990/LogOutput.log)

**Comment by viliger2** [comment]
You don't have a single custom character installed. Either consider re-reading the mod page or post your BepinEx\CharacterAPI folder

**Comment by arrigit** [comment]
lol sorry i posted the wrong log from another testing i was doing :p 
[LogOutput.log](https://github.com/viliger2/CharacterAPI_BRCCCLoader/files/12786407/LogOutput.log)

**Comment by viliger2** [comment]
You have 3 characters loaded, go to cypher and they should be there.

**Comment by arrigit** [comment]
ok i will try today thank you sorry 4 the trouble!!
